name: Deploy EOMS to Azure Web App - eoms-dispatch

on:
  push:
    branches:
      - production
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: eoms-dispatch
  PYTHON_VERSION: '3.11'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Validate app
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m py_compile app.py

      - name: Deploy repository to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7B58759A34D04AFB831B18678A70C081 }}
          package: .